### PR TITLE
Fix changelog where first release isn't first

### LINKED ISSUE #57: Invalid reference link definition when new release is first numerically
When the release being prepared is the _first_ release numerically, the reference link definition generated will be invalid.

For example, if preparing a v0.1.0 release for a project that already has a v1.0.0 release, it will generate this reference link definition: `${repoUrl}/compare/vundefined...v0.1.0`.

In these cases, where we don't have any release to compare to, we just just link the tag itself.

### PR DESCRIPTION
**Pull request by Gudahtt**
`auto-changelog` will now correctly update and validate changelogs where the first release chronologically is different than the first release numerically.

A test has been added to ensure such a changelog is now validated correctly. This test fails on `main`.

Fixes #57

### CODE REVIEW

File: src/changelog.ts [hunk 1]
```diff
@@ -139,20 +139,21 @@ function stringifyLinkReferenceDefinitions(
   // patch releases on older releases can be accomodated.
   const releaseLinkReferenceDefinitions = releases
     .map(({ version }) => {
+      let diffUrl;
       if (version === orderedReleases[orderedReleases.length - 1]) {
```
Comment (rekmarks) [inline src/changelog.ts:143]: My only feedback is that `orderedReleases` (and really the releases param) could be documented / named such that it's immediately obvious that the releases are sorted in chronological order.k

**Review by rekmarks — APPROVED** [review]
LGTM! Just one nit.

File: src/changelog.ts (hunk 1 above)
Comment (Gudahtt) [reply src/changelog.ts:143]: Good call, I'll rename this

Comment (Gudahtt) [reply src/changelog.ts]: Done in https://github.com/MetaMask/auto-changelog/pull/76/commits/027e394c92bc254503aa153ad009ea6541f57282

**Review by rekmarks — APPROVED** [review]
I'm sold.
